%T Spectroscopy:  Instrumentation and Applications to the Galaxy and to the Large Scale Structure of the Universe
%A Brown, Warren R.
%F AA(Harvard University)
%D 2002/05
%G Zenodo
%K spectroscopy, galaxies, Milky Way, spectrograph design
%B I study the design and construction of modern spectrographs and use spectrographs to study the properties of galaxies in a local galaxy redshift survey and to study the structure of our own Galaxy from a stellar radial velocity survey.&nbsp; I perform four scientific studies based on 64 square degrees of deep V- and R-band imaging I obtained with the 8 CCD Mosaic camera on the Kitt Peak National Observatory 0.9 m telescope.&nbsp; I study 1) the local galaxy luminosity function, 2) low surface brightness galaxies, 3) UV excess galaxies, and 4) the structure of the Galactic halo.</p>I find surprisingly identical V- and R-band faint end slopes of the local galaxy luminosity function, &alpha;=-1.07 \pm 0.09, and local luminosity densities in essential agreement with the recent 2dF and SDSS determinations. All low surface brightness galaxies fall in the large scale structure delineated by high surface brightness galaxies and contribute little to the total luminosity density of the local Universe.&nbsp; I show that a sample of ultraviolet (UV) excess galaxies are likely Wolf-Rayet galaxies, starburst galaxies with strong UV emission lines that can double or triple the flux through the UV bandpass at large redshifts and can skew the selection function to large redshifts.&nbsp; I use blue horizontal branch stars to trace the structure of the Milky Way halo and find evidence for systematic motions in the inner halo as well as a probable star stream 6 \pm 1.4 kpc above the Galactic plane.</p>My instrumentation work includes a detailed thermal analysis of Binospec, a wide-field, multi-object spectrograph for the MMT.&nbsp; I find that a well-insulated spectrograph design will have a time constant of 36 hours, leading to ~0.1 deg C temperature gradients in the refractive optics and ~0.1 pixel/hr image shifts at the detector.
%I PDF: https://zenodo.org/record/16839/files/wbrown2002.pdf; DOI: 10.5281/zenodo.16839; OPEN: 1; ELECTR: http://zenodo.org/record/16839

