MONTH_TO_NUMBER = {'jan':1, 'feb':2, 'mar':3, 'apr':4, 'may':5, 'jun':6,
                   'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12}
# APS Journal dictionary: used by parsers/aps.py to get the bibstem

APS_PUBLISHER_IDS = {'PRL': 'PhRvL', 'PRX': 'PhRvX', 'RMP': 'RvMP',
                     'PRA': 'PhRvA', 'PRB': 'PhRvB', 'PRC': 'PhRvC',
                     'PRD': 'PhRvD', 'PRE': 'PhRvE', 'PRAB': 'PhRvS',
                     'PRSTAB': 'PhRvS', 'PRAPPLIED': 'PhRvP',
                     'PRFLUIDS': 'PhRvF', 'PRMATERIALS': 'PhRvM',
                     'PRPER': 'PRPER', 'PRSTPER': 'PRSTP', 'PR': 'PhRv',
                     'PRI': 'PhRvI','PHYSICS': 'PhyOJ'}

APS_ASTRO_KEYWORDS = [
            'Accretion disk & black-hole plasma',
            'Active & peculiar galaxies',
            'Alternative gravity theories',
            'Anthropic considerations',
            'Asteroids, meteors, & meteorites',
            'Astronomical black holes',
            'Astronomical masses & mass distributions',
            'Astrophysical & cosmological simulations',
            'Astrophysical electromagnetic fields',
            'Astrophysical fluid dynamics',
            'Astrophysical jets',
            'Astrophysical studies of gravity',
            'Baryogenesis & leptogenesis',
            'Big bang nucleosynthesis',
            'Binary stars',
            'Canonical quantum gravity',
            'Classical black holes',
            'Composition of astronomical objects',
            'Cosmic microwave background',
            'Cosmic ray & astroparticle detectors',
            'Cosmic ray acceleration',
            'Cosmic ray composition & spectra',
            'Cosmic ray propagation',
            'Cosmic ray sources',
            'Cosmic rays & astroparticles',
            'Cosmic strings & domain walls',
            'Cosmological constant',
            'Cosmological parameters',
            'Cosmology',
            'Dark energy',
            'Dark matter',
            'Dark matter detectors',
            'Distances, redshifts, & velocities',
            'Electromagnetic radiation astronomy',
            'Evolution of the Universe',
            'Experimental studies of gravity',
            'Explosive burning',
            'Extrasolar neutrino astronomy',
            'Extrasolar planets',
            'Fluid planets',
            'Fluids & classical fields in curved spacetime',
            'Formation & evolution of stars & galaxies',
            'Galactic disks',
            'Galactic halos',
            'Galactic nuclei & quasars',
            'Galaxies',
            'Galaxy clusters',
            'Gamma ray astronomy',
            'Gamma ray bursts',
            'General relativity',
            'General relativity equations & solutions',
            'General relativity formalism',
            'Gravitation',
            'Gravitational lenses',
            'Gravitational wave detection',
            'Gravitational wave detectors',
            'Gravitational wave sources',
            'Gravitational waves',
            'Gravity in dimensions other than four',
            'H & He burning',
            'Hydrostatic stellar nucleosynthesis',
            'Inflation',
            'Intergalactic medium',
            'Interplanetary magnetic field',
            'Interstellar medium',
            'Laboratory studies of gravity',
            'Laboratory studies of space & astrophysical plasmas',
            'Large scale structure of the Universe',
            'Loop quantum gravity',
            'Massive compact halo objects',
            'Milky Way',
            'Neutrino detectors',
            'Neutron stars & pulsars',
            'Normal galaxies',
            'Normal stars',
            'Novae & supernovae',
            'Nuclear astrophysics',
            'Nuclear physics of explosive environments',
            'Nucleosynthesis in explosive environments',
            'Numerical relativity',
            'Numerical simulations in gravitation & astrophysics',
            'Optical, UV, & IR astronomy',
            'Particle astrophysics',
            'Particle dark matter',
            'Planetary satellites & rings',
            'Planets & planetary systems',
            'Pre-main-sequence stars',
            'Primordial magnetic fields',
            'Quantum aspects of black holes',
            'Quantum cosmology',
            'Quantum fields in curved spacetime',
            'Quantum gravity',
            'Radio, microwave, & sub-mm astronomy',
            'Relativistic aspects of cosmology',
            'Singularities In general relativity',
            'Sky surveys',
            'Solar neutrinos',
            'Solar system & its planets',
            'Solid-surface planets',
            'Space & astrophysical plasma',
            'Space charge in beams',
            'Space science',
            'Space weather',
            'Spacetime symmetries',
            'Spacetime topology & causal structure',
            'Stars',
            'Stellar plasmas',
            'Sun',
            'Supergravity',
            'Supernova remnants',
            'Telescopes',
            'Transient & explosive astronomical phenomena',
            'Unruh effect',
            'Variable & peculiar stars',
            'X ray astronomy',
            'X ray bursts',
            'r process',
            's process'
]

IOP_PUBLISHER_IDS = {'rnaas': u'RNAAS', 'apj': u'ApJ'}
IOP_JOURNAL_NAMES = {'rnaas': u'Research Notes of the American Astronomical Society'}

JATS_TAGS_DANGER = ['php','script','css']

JATS_TAGS_MATH = ['inline-formula',
            'mml:math',
            'mml:semantics',
            'mml:mrow',
            'mml:munder',
            'mml:mo',
            'mml:mi',
            'mml:msub',
            'mml:mover',
            'mml:mn',
            'mml:annotation'
]

JATS_TAGS_HTML = ['sub','sup','a','astrobj']

JATS_TAGSET = {'title':JATS_TAGS_MATH + JATS_TAGS_HTML,
            'abstract':JATS_TAGS_MATH + JATS_TAGS_HTML + ['pre','br'],
            'comments':JATS_TAGS_MATH + JATS_TAGS_HTML + ['pre','br'],
            'affiliations':['email','orcid'],
            'keywords':['astrobj']
        }

UAT_ASTRO_KEYWORDS = ["53 Persei stars",
            "A dwarf stars",
            "A giant stars",
            "A stars",
            "A subdwarf stars",
            "A subgiant stars",
            "A supergiant stars",
            "Abell clusters",
            "Absolute magnitude",
            "Abundance ratios",
            "Accelerating universe",
            "Accretion",
            "Achondrites",
            "Active galactic nuclei",
            "Active galaxies",
            "Active solar chromosphere",
            "Active solar corona",
            "Active sun",
            "Adaptive interferometry",
            "Ae stars",
            "Aerolites",
            "Aeronomy",
            "Affine invariant",
            "AGN host galaxies",
            "Akaike information criterion",
            "Alfven waves",
            "Algol variable stars",
            "Algorithms",
            "All-sky cameras",
            "Almanacs",
            "Alt-azimuth mounts",
            "Alternatives to cosmic inflation",
            "Altitude angle",
            "AM Canum Venaticorum stars",
            "AM Herculis stars",
            "Am stars",
            "Amateur astronomers",
            "Amateur astronomy",
            "Amor group",
            "Amorphous irregular galaxies",
            "Analytical mathematics",
            "Andromeda Galaxy",
            "Angular separation",
            "Annual equation",
            "Annual parallax",
            "Annular eclipses",
            "Anomalistic month",
            "Anomalous Cepheid variable stars",
            "Ansae",
            "Antapex",
            "Antarctic observatories",
            "Anthropic principle",
            "Antumbra",
            "Ap stars",
            "Apastron",
            "Aperiodic comets",
            "Aperture synthesis",
            "Apex",
            "Aphelion",
            "Apocenter",
            "Apogee",
            "Apollo group",
            "Apparent magnitude",
            "Apparent position",
            "Apparent superluminal motion",
            "Apsidal motion",
            "Apsides",
            "Archaeoastronomy",
            "Argument of perigee",
            "Argument of perihelion",
            "Armillary spheres",
            "Artificial satellites",
            "Ascending node",
            "Asteroid belt",
            "Asteroid occultation",
            "Asteroids",
            "Asteroseismology",
            "Astrobiology",
            "Astrochemistry",
            "Astrodynamics",
            "Astrographic catalogs",
            "Astroinformatics",
            "Astrometric binary stars",
            "Astrometry",
            "Astronomers",
            "Astronomical coordinate systems",
            "Astronomical detectors",
            "Astronomical instrumentation",
            "Astronomical location",
            "Astronomical methods",
            "Astronomical models",
            "Astronomical object identification",
            "Astronomical optics",
            "Astronomical radiation sources",
            "Astronomical reference materials",
            "Astronomical research",
            "Astronomical seeing",
            "Astronomical sextants",
            "Astronomical simulations",
            "Astronomical site protection",
            "Astronomical techniques",
            "Astronomical unit",
            "Astronomy data acquisition",
            "Astronomy data analysis",
            "Astronomy data modeling",
            "Astronomy data reduction",
            "Astronomy data visualization",
            "Astronomy databases",
            "Astronomy software",
            "Astronomy web services",
            "Astrophotography",
            "Astrophysical black holes",
            "Astrophysical dust processes",
            "Astrophysical explosive burning",
            "Astrophysical fluid dynamics",
            "Astrophysical magnetism",
            "Astrophysical masers",
            "Astrophysical processes",
            "Astrophysicists",
            "Astrosphere interstellar medium interactions",
            "Astrospheres",
            "Astrostatistics",
            "Astrostatistics distributions",
            "Astrostatistics strategies",
            "Astrostatistics techniques",
            "Astrostatistics tools",
            "Asymptotic giant branch",
            "Asymptotic giant branch stars",
            "Ataxites",
            "Aten group",
            "Atira group",
            "Atmospheric circulation",
            "Atmospheric effects",
            "Atmospheric extinction",
            "Atmospheric refraction",
            "Atmospheric science",
            "Atmospheric scintillation",
            "Atmospheric tides",
            "Atomic data benchmarking",
            "Atomic interferometry",
            "Atomic physics",
            "Atomic spectroscopy",
            "Australites",
            "Automated telescopes",
            "Automatic patrol telescopes",
            "Autumnal equinox",
            "Azimuth",
            "B dwarf stars",
            "B giant stars",
            "B stars",
            "B subdwarf stars",
            "B subgiant stars",
            "B supergiant stars",
            "B(e) stars",
            "Baade-Wesselink method",
            "Baily's beads",
            "Baker-Nunn cameras",
            "Barium stars",
            "Barred spiral galaxies",
            "Baryogenesis",
            "Baryon acoustic oscillations",
            "Baryon density",
            "Baryonic dark matter",
            "Bautz-Morgan type",
            "Bayes factor",
            "Bayes' Theorem",
            "Bayesian information criterion",
            "Bayesian statistics",
            "Be stars",
            "Bediasites",
            "Bekenstein-Hawking entropy",
            "Bessel photometry",
            "Beta Cepheid variable stars",
            "Beta Lyrae stars",
            "Bianchi cosmology",
            "Big Bang nucleosynthesis",
            "Big Bang theory",
            "Binary pulsars",
            "Binary stars",
            "Biomarkers",
            "Bipolar nebulae",
            "Bipolar sunspot groups",
            "BL Herculis stars",
            "BL Lacertae objects",
            "Black hole physics",
            "Black hole spin-flip",
            "Black hole thermodynamics",
            "Black holes",
            "Blank fields",
            "Blazars",
            "Blue cloud galaxies",
            "Blue compact dwarf galaxies",
            "Blue loop",
            "Blue straggler stars",
            "Blueshifted",
            "Bode's law",
            "Bok globules",
            "Bolides",
            "Bolometric correction",
            "Bondi accretion",
            "Bootstrap",
            "Borasisi",
            "Bouwers telescope",
            "Bp stars",
            "Brane cosmology",
            "Bright nebulae",
            "Brightest cluster galaxies",
            "Brightness temperature",
            "Broad band photometry",
            "Broad-absorption line quasar",
            "Brown dwarfs",
            "Burkert profile",
            "Burst astrophysics",
            "BV photometry",
            "BW stars",
            "BY Draconis stars",
            "Calendars",
            "Cape photometry",
            "Cape RI photometry",
            "Carbon burning",
            "Carbon dioxide",
            "Carbon flashes",
            "Carbon planets",
            "Carbon stars",
            "Carbon-nitrogen cycle",
            "Carbonaceous chondrites",
            "Carbonaceous grains",
            "Cassegrain telescopes",
            "Cataclysmic variable stars",
            "Catadioptric telescopes",
            "Catalogs",
            "Caustic crossing",
            "CCD observation",
            "CCD photometry",
            "cD galaxies",
            "Celestial equator",
            "Celestial mechanics",
            "Celestial objects catalogs",
            "Celestial poles",
            "Celestial sphere",
            "CEMP stars",
            "Centaurs",
            "Center of mass",
            "Center to limb observations",
            "Cepheid distance",
            "Cepheid variable stars",
            "Ceres",
            "CH stars",
            "Chandrasekhar limit",
            "Chaos",
            "Charge exchange ionization",
            "Charge exchange recombination",
            "Charged black holes",
            "Chemical abundances",
            "Chemical enrichment",
            "Chemically peculiar giant stars",
            "Chemically peculiar stars",
            "Chi-squared statistic",
            "Chlorofluorocarbons",
            "Chondrites",
            "Chondrules",
            "Chthonian planets",
            "CII region",
            "Circular orbits",
            "Circumgalactic medium",
            "Circumstellar clouds",
            "Circumstellar disks",
            "Circumstellar dust",
            "Circumstellar envelopes",
            "Circumstellar gas",
            "Circumstellar grains",
            "Circumstellar masers",
            "Circumstellar matter",
            "Circumstellar shells",
            "Cirrus castellanus",
            "Cirrus fibratus",
            "Cirrus floccus",
            "Cirrus spissatus",
            "Cirrus uncinus",
            "Cirrus vertebratus",
            "Classical black holes",
            "Classical Kuiper belt objects",
            "Classical novae",
            "Classical T Tauri stars",
            "Classification",
            "Classification systems",
            "Close binary stars",
            "Close encounters",
            "Closed universe",
            "Cloud computing",
            "Cloud monitors",
            "Clouds",
            "Clustering",
            "CMBR detectors",
            "CN stars",
            "CNO anomaly",
            "CO line emission",
            "Cocoon stars",
            "Coelostats",
            "Cold dark matter",
            "Cold neutral medium",
            "Collapsing clouds",
            "Collimation",
            "Collision processes",
            "Collisional broadening",
            "Color equation",
            "Coma Cluster",
            "Comas",
            "Comet interiors",
            "Comet tail streamers",
            "Comet tails",
            "Cometary atmospheres",
            "Cometary globules",
            "Cometary ionospheres",
            "Cometary nebulae",
            "Cometary studies",
            "Comets",
            "Compact binary stars",
            "Compact dwarf galaxies",
            "Compact galaxies",
            "Compact H II region",
            "Compact nebulae",
            "Compact objects",
            "Compact radiation sources",
            "Companion galaxies",
            "Companion stars",
            "Comparison stars",
            "Computational astronomy",
            "Computational methods",
            "Confidence interval",
            "Conical singularities",
            "Conjunction",
            "Constellations",
            "Contact binary stars",
            "Convolutional neural networks",
            "Cool cores",
            "Cool intergalactic medium",
            "Cooling flows",
            "Core-collapse supernovae",
            "Coronographic imaging",
            "Corotating streams",
            "Cosmic abundances",
            "Cosmic anisotropy",
            "Cosmic background radiation",
            "Cosmic electrodynamics",
            "Cosmic inflation",
            "Cosmic isotropy",
            "Cosmic magnetic fields theory",
            "Cosmic microwave background radiation",
            "Cosmic noise",
            "Cosmic ray astronomy",
            "Cosmic ray detectors",
            "Cosmic ray nucleosynthesis",
            "Cosmic ray showers",
            "Cosmic ray sources",
            "Cosmic rays",
            "Cosmic web",
            "Cosmochemistry",
            "Cosmochronology",
            "Cosmogony",
            "Cosmological constant",
            "Cosmological constant experiments",
            "Cosmological evolution",
            "Cosmological models",
            "Cosmological neutrinos",
            "Cosmological parameters",
            "Cosmological parameters from large-scale structure",
            "Cosmological perturbation theory",
            "Cosmological phase transitions",
            "Cosmology",
            "Credible region",
            "Cross-validation",
            "Curvature singularities",
            "Curved space",
            "D galaxies",
            "D layer",
            "DA stars",
            "Damped Lyman-alpha systems",
            "Dark adaption",
            "Dark energy",
            "Dark interstellar clouds",
            "Dark matter",
            "Dark matter density",
            "Dark matter detectors",
            "Dark matter distribution",
            "DB stars",
            "DC stars",
            "DDO classification",
            "DDO photometry",
            "de Sitter universe",
            "De Vaucouleurs Sandage classification",
            "De-excitation rates",
            "Debris disks",
            "Deceleration parameter",
            "Declination",
            "Deconvolution",
            "Deep space probes",
            "Degenerate matter",
            "Delta Cepheid variable stars",
            "Delta Delphini variable stars",
            "Delta Scuti variable stars",
            "Delta sunspots",
            "Dense interstellar clouds",
            "Density parameters",
            "Density wave model",
            "Descending node",
            "Detached binary stars",
            "Detached objects",
            "Detection",
            "Deucalion",
            "Diamond ring effect",
            "Dielectronic recombination",
            "Diffuse interstellar bands",
            "Diffuse interstellar clouds",
            "Diffuse molecular clouds",
            "Diffuse nebulae",
            "Diffuse radiation",
            "Diffuse x-ray background",
            "Dimensionality reduction",
            "Dirac cosmology",
            "Direct detection interferometry",
            "Direct imaging",
            "Dirty snowball theory",
            "Discrete radio sources",
            "Disk flaring",
            "Disk galaxies",
            "Distance indicators",
            "Distance measure",
            "Distributed computing",
            "Diurnal parallax",
            "DO stars",
            "Dobsonian telescopes",
            "Domes",
            "Doppler imaging",
            "Doppler shift",
            "Double galaxies",
            "Double quasars",
            "Double-mode Cepheid variable stars",
            "Double-mode pulsation",
            "Double-mode variable stars",
            "DQ Herculis stars",
            "DQ stars",
            "Draco dwarf galaxy",
            "Dredge-up",
            "Drift scan imaging",
            "Dumbbell galaxies",
            "Dust continuum emission",
            "Dust nebulae",
            "Dust shells",
            "Dwarf elliptical galaxies",
            "Dwarf galaxies",
            "Dwarf irregular galaxies",
            "Dwarf novae",
            "Dwarf planets",
            "Dwarf spheroidal galaxies",
            "Dwarf stars",
            "Dynamical evolution",
            "Dynamical friction",
            "Dynamical parallax",
            "DZ stars",
            "E layer",
            "E+A galaxies",
            "E-folding time",
            "Early astronomical instruments",
            "Early stellar evolution",
            "Early universe",
            "Early-type emission stars",
            "Early-type galaxies",
            "Early-type stars",
            "Early-type supergiant stars",
            "Early-type variable stars",
            "Earth (planet)",
            "Earth atmosphere",
            "Earth trojans",
            "Earth-moon system",
            "Eccentric anomaly",
            "Eccentricity",
            "Eclipses",
            "Eclipsing binary minima timing method",
            "Eclipsing binary stars",
            "Ecliptic coordinate system",
            "Ecliptic latitude",
            "Ecliptic longitude",
            "Ecliptic poles",
            "Educational software",
            "Effective temperature",
            "Einstein field equations",
            "Einstein rings",
            "Einstein universe",
            "Ejecta",
            "Electron impact ionization",
            "Ellerman Bombs",
            "Ellipsoidal variable stars",
            "Elliptical galaxies",
            "Elliptical orbits",
            "Emerging flux tubes",
            "Emission line galaxies",
            "Emission line stars",
            "Emission nebulae",
            "Ephemeral active regions",
            "Ephemerides",
            "Equation of the center",
            "Equator position",
            "Equatorial coordinate system",
            "Equatorial mounts",
            "Equatorial zone",
            "Equinox",
            "Ergosphere",
            "Eris",
            "Eruptive phenomena",
            "Eruptive variable stars",
            "Ethnoastronomy",
            "Evaporating gaseous globules",
            "Event horizons",
            "Evolution equation",
            "Evolved stars",
            "Excitation rates",
            "Exoplanet astronomy",
            "Exoplanet atmospheres",
            "Exoplanet atmospheric composition",
            "Exoplanet atmospheric variability",
            "Exoplanet catalogs",
            "Exoplanet detection methods",
            "Exoplanet dynamics",
            "Exoplanet evolution",
            "Exoplanet formation",
            "Exoplanet plate tectonics",
            "Exoplanet rings",
            "Exoplanet structure",
            "Exoplanet surface characteristics",
            "Exoplanet surface composition",
            "Exoplanet surface variability",
            "Exoplanet systems",
            "Exoplanet tides",
            "Exoplanets",
            "Exosphere",
            "Exozodiacal dust",
            "Expanding stellar envelopes",
            "Expanding universe",
            "Expectation-Maximization Algorithm",
            "Experimental models",
            "Experimental techniques",
            "Explosive nucleosynthesis",
            "Extended radiation sources",
            "Extinction",
            "Extragalactic astronomy",
            "Extragalactic magnetic fields",
            "Extragalactic radio sources",
            "Extrasolar gas giants",
            "Extrasolar ice giants",
            "Extrasolar radiation",
            "Extrasolar rocky planets",
            "Extreme carbon stars",
            "Extreme horizontal branch stars",
            "Extrinsic variable stars",
            "F dwarf stars",
            "F giant stars",
            "F layer",
            "F stars",
            "F subdwarf stars",
            "F subgiant stars",
            "F supergiant stars",
            "F test",
            "Faber-Jackson distance",
            "Fabry-Perot interferometers",
            "Faint blue stars",
            "Fanaroff-Riley radio galaxies",
            "Far infrared astronomy",
            "Far infrared interferometry",
            "Fast Fourier transform",
            "Fast novae",
            "Fast solar wind",
            "Few-body systems",
            "Field galaxies",
            "Field of view",
            "Field stars",
            "Filamentary nebulae",
            "Finding charts",
            "Finding lists",
            "Fireballs",
            "Fisher's Information",
            "FK catalog",
            "FK Comae stars",
            "Flare stars",
            "Flash spectra",
            "Flash stars",
            "Flat space",
            "Flux calibration",
            "Flyby missions",
            "Forbush effect",
            "Fornax dwarf spheroidal galaxy",
            "Free floating planets",
            "Friedmann universe",
            "Friedmann-Robertson-Walker metric",
            "Frozen in elements",
            "FU Orionis stars",
            "Fundamental parameters of stars",
            "G dwarf stars",
            "G giant stars",
            "G stars",
            "G subdwarf stars",
            "G subgiant stars",
            "G supergiant stars",
            "Galactic abundances",
            "Galactic and extragalactic astronomy",
            "Galactic anticenter",
            "Galactic bulge",
            "Galactic center",
            "Galactic coordinate system",
            "Galactic cosmic rays",
            "Galactic latitude",
            "Galactic longitude",
            "Galactic poles",
            "Galactic radio sources",
            "Galactic winds",
            "Galaxies",
            "Galaxy abundances",
            "Galaxy accretion",
            "Galaxy accretion disks",
            "Galaxy ages",
            "Galaxy anticenters",
            "Galaxy bulges",
            "Galaxy chemical evolution",
            "Galaxy circumnuclear disk",
            "Galaxy classification systems",
            "Galaxy cluster counts",
            "Galaxy clusters",
            "Galaxy collisions",
            "Galaxy colors",
            "Galaxy counts",
            "Galaxy dark matter halos",
            "Galaxy disks",
            "Galaxy distances",
            "Galaxy dynamics",
            "Galaxy encounters",
            "Galaxy environments",
            "Galaxy equators",
            "Galaxy evolution",
            "Galaxy formation",
            "Galaxy fountains",
            "Galaxy groups",
            "Galaxy infall",
            "Galaxy interactions",
            "Galaxy jets",
            "Galaxy kinematics",
            "Galaxy luminosities",
            "Galaxy magnetic fields",
            "Galaxy magnitudes",
            "Galaxy mass distribution",
            "Galaxy masses",
            "Galaxy mergers",
            "Galaxy nuclei",
            "Galaxy pairs",
            "Galaxy photometry",
            "Galaxy physics",
            "Galaxy planes",
            "Galaxy processes",
            "Galaxy properties",
            "Galaxy quenching",
            "Galaxy radial velocities",
            "Galaxy radii",
            "Galaxy rotation",
            "Galaxy rotation curves",
            "Galaxy spheroids",
            "Galaxy spurs",
            "Galaxy stellar content",
            "Galaxy stellar disks",
            "Galaxy stellar halos",
            "Galaxy structure",
            "Galaxy tides",
            "Galaxy triplets",
            "Galaxy voids",
            "Galaxy winds",
            "Galilean satellites",
            "Gamma Cassiopeiae stars",
            "Gamma distribution",
            "Gamma Doradus variable stars",
            "Gamma-ray astronomy",
            "Gamma-ray bursters",
            "Gamma-ray bursts",
            "Gamma-ray detectors",
            "Gamma-ray lines",
            "Gamma-ray observatories",
            "Gamma-ray sources",
            "Gamma-ray telescopes",
            "Gamma-ray transient sources",
            "Gamma-rays",
            "Gas-to-dust ratio",
            "Gaseous nebulae",
            "Gaussian mixture model",
            "Gaussian Processes regression",
            "Gegenschein",
            "General relativity",
            "Geneva photometry",
            "Geocentric orbit",
            "Geocorona",
            "Geodesics",
            "Geomagnetic fields",
            "Geostationary satellites",
            "Geosynchronous satellites",
            "Giant branch",
            "Giant elliptical galaxies",
            "Giant galaxies",
            "Giant molecular clouds",
            "Giant radio galaxies",
            "Giant stars",
            "Gibbs Sampler",
            "Globular star clusters",
            "Gould Belt",
            "GPU computing",
            "Gravastars",
            "Gravitation",
            "Gravitational collapse",
            "Gravitational deflection",
            "Gravitational disruption",
            "Gravitational energy",
            "Gravitational equilibrium",
            "Gravitational fields",
            "Gravitational instability",
            "Gravitational interaction",
            "Gravitational lensing",
            "Gravitational lensing shear",
            "Gravitational microlensing",
            "Gravitational singularities",
            "Gravitational wave astronomy",
            "Gravitational wave detectors",
            "Gravitational wave sources",
            "Gravitational waves",
            "Gravity anomaly",
            "Gravity darkening",
            "Grazing incidence telescopes",
            "Great Attractor",
            "Green valley galaxies",
            "Greenhouse gases",
            "Gregorian telescopes",
            "Ground telescopes",
            "Ground-based astronomy",
            "Gunn photometry",
            "Godel universe",
            "H alpha photometry",
            "H beta photometry",
            "H I line emission",
            "H I regions",
            "H II regions",
            "H-alpha stars",
            "Habitable planets",
            "Habitable zone",
            "Hadron barrier",
            "Hall thrusters",
            "Halo stars",
            "Hardness ratio",
            "Haro galaxies",
            "Haumea",
            "Hawking radiation",
            "Hayashi track",
            "Heavy metal stars",
            "Heliocentric orbit",
            "Heliopause",
            "Helioseismic pulsations",
            "Helioseismology",
            "Heliosheath",
            "Heliosphere",
            "Heliostats",
            "Helium burning",
            "Helium weak stars",
            "Helium-poor stars",
            "Helium-rich stars",
            "Helmholtz-Kelvin contraction",
            "Henry Draper catalog",
            "Henyey track",
            "Herbig Ae/Be stars",
            "Herbig-Haro objects",
            "Hertzsprung gap",
            "Hertzsprung Russell diagram",
            "Heterodyne interferometry",
            "Heterodyne receivers",
            "HI shells",
            "Hickson compact group",
            "Hierarchical cosmology",
            "Hierarchical models",
            "High altitude balloons",
            "High energy astrophysics",
            "High latitude field",
            "High mass X-ray binary stars",
            "High resolution spectroscopy",
            "High time resolution astrophysics",
            "High-energy cosmic radiation",
            "High-luminosity active galactic nuclei",
            "High-redshift galaxies",
            "High-redshift galaxy clusters",
            "High-velocity clouds",
            "High-velocity stars",
            "Hilda group",
            "Hirayama families",
            "History of astronomy",
            "Holmberg radius",
            "Holmium stars",
            "Holographic interferometry",
            "Horizontal branch",
            "Horizontal branch stars",
            "Horizontal coordinate system",
            "Horizontal parallax",
            "Hot dark matter",
            "Hot intergalactic medium",
            "Hot ionized medium",
            "Hot Jupiters",
            "Hot Neptunes",
            "Hour angle",
            "HST photometry",
            "Hubble classification scheme",
            "Hubble constant",
            "Hubble diagram",
            "Hubble radius",
            "Hubble Space Telescope",
            "Hubble time",
            "Hubble's law",
            "Humidity",
            "Hungaria group",
            "Huya",
            "Hydrodynamical simulations",
            "Hydrodynamics",
            "Hydrogen burning",
            "Hydrogen deficient stars",
            "Hydrosphere",
            "Hydroxyl masers",
            "Hydroxyl sources",
            "Hyperbolic orbit",
            "Hypergiant stars",
            "Hypernovae",
            "Hypervelocity stars",
            "Hz Herculis X-ray binary stars",
            "Ice destruction",
            "Ice formation",
            "Impact phenomena",
            "Importance sampling",
            "Inclination",
            "Indochinites",
            "Inflationary universe",
            "Infrared Astronomical Satellite",
            "Infrared astronomy",
            "Infrared dark clouds",
            "Infrared excess",
            "Infrared excess galaxies",
            "Infrared galaxies",
            "Infrared observatories",
            "Infrared photometry",
            "Infrared sources",
            "Infrared telescopes",
            "Initial conditions of the universe",
            "Initial mass function",
            "Inner planets",
            "Instability strip",
            "Integrated magnitude",
            "Interacting binary stars",
            "Interacting galaxies",
            "Intercloud medium",
            "Interdisciplinary astronomy",
            "Interferometers",
            "Interferometric binary stars",
            "Interferometric correlation",
            "Interferometry",
            "Intergalactic abundances",
            "Intergalactic clouds",
            "Intergalactic dust clouds",
            "Intergalactic filaments",
            "Intergalactic gas",
            "Intergalactic medium",
            "Intergalactic medium phases",
            "Intergalactic voids",
            "Intermediate-mass black holes",
            "Intermediate-type stars",
            "Internal waves",
            "Interplanetary discontinuities",
            "Interplanetary dust",
            "Interplanetary gas",
            "Interplanetary grains",
            "Interplanetary magnetic fields",
            "Interplanetary medium",
            "Interplanetary particle acceleration",
            "Interplanetary physics",
            "Interplanetary scintillation",
            "Interplanetary shocks",
            "Interplanetary turbulence",
            "Interstellar absorption",
            "Interstellar abundances",
            "Interstellar atomic gas",
            "Interstellar clouds",
            "Interstellar cyclotron emission",
            "Interstellar dust",
            "Interstellar dust extinction",
            "Interstellar dust processes",
            "Interstellar dynamics",
            "Interstellar emissions",
            "Interstellar extinction",
            "Interstellar filaments",
            "Interstellar line absorption",
            "Interstellar line emission",
            "Interstellar magnetic fields",
            "Interstellar masers",
            "Interstellar medium",
            "Interstellar medium wind",
            "Interstellar molecules",
            "Interstellar phases",
            "Interstellar plasma",
            "Interstellar radiation field",
            "Interstellar reddening",
            "Interstellar scattering",
            "Interstellar scintillation",
            "Interstellar synchrotron emission",
            "Interstellar thermal emission",
            "Intracluster medium",
            "Intrinsic variable stars",
            "Ionization",
            "Ionosphere",
            "Ionospheric scintillation",
            "IRAS galaxies",
            "Iron meteorites",
            "Irregular cadence",
            "Irregular galaxies",
            "Irregular natural satellites (Extrasolar)",
            "Irregular satellites",
            "Irregular variable stars",
            "Isothermal sphere profile",
            "Isotope shifts",
            "Isotopic abundances",
            "Ixion",
            "Jeans mass",
            "Jets",
            "Johnson photometry",
            "Jovian satellites",
            "Jupiter",
            "Jupiter trojans",
            "K dwarf stars",
            "K giant stars",
            "K stars",
            "K subdwarf stars",
            "K subgiant stars",
            "K supergiant stars",
            "Kappa mechanism",
            "Kapteyn Selected Areas",
            "Keplerian orbit",
            "Kerr black holes",
            "Kerr metric",
            "Kerr-Newman black holes",
            "Kinematic parallax",
            "Kirkwood gap",
            "Kolmogorov-Smirnov test",
            "Kreutz Sungrazers",
            "Kron-Cousins photometry",
            "Kruskal diagram",
            "Kuiper belt",
            "Kullback-Leibler distance",
            "L dwarfs",
            "L galaxies",
            "L subdwarfs",
            "Laboratory astrophysics",
            "Lagrangian points",
            "Lambda density",
            "Lambda Eridani stars",
            "Land-atmosphere interactions",
            "Landers",
            "Large Magellanic Cloud",
            "Large-scale structure of the universe",
            "Laser guide stars",
            "Laser interferometry",
            "Late stellar evolution",
            "Late-type dwarf stars",
            "Late-type galaxies",
            "Late-type giant stars",
            "Late-type stars",
            "Late-type supergiant stars",
            "Lb variable stars",
            "Lc variable stars",
            "Lemaitre universe",
            "Lenticular galaxies",
            "Leptogenesis",
            "Libration",
            "Light curve classification",
            "Light curves",
            "Light year",
            "LIGO",
            "Likelihood ratio test",
            "Limb brightening",
            "Limb darkening",
            "Limiting magnitude",
            "Line intensities",
            "Line of sight",
            "Line positions",
            "Linear regression",
            "LINER galaxies",
            "Lithium stars",
            "Lithosphere",
            "Local Group",
            "Logos",
            "Lomb-Scargle periodogram",
            "Long baseline interferometers",
            "Long baseline interferometry",
            "Long period comets",
            "Long period variable stars",
            "Longitude of the ascending node",
            "Longitude of the descending node",
            "Low mass stars",
            "Low surface brightness galaxies",
            "Low-density fields",
            "Low-luminosity active galactic nuclei",
            "Low-mass X-ray binary stars",
            "Luminosity classification",
            "Luminosity function",
            "Luminous arcs",
            "Luminous blue variable stars",
            "Luminous infrared galaxies",
            "Lunar atmosphere",
            "Lunar composition",
            "Lunar craters",
            "Lunar domes",
            "Lunar eclipses",
            "Lunar evolution",
            "Lunar features",
            "Lunar geochronology",
            "Lunar geodesy",
            "Lunar gravitational field",
            "Lunar highlands",
            "Lunar impacts",
            "Lunar interior",
            "Lunar magnetic fields",
            "Lunar maria",
            "Lunar mineralogy",
            "Lunar mountains",
            "Lunar node regression",
            "Lunar occultation",
            "Lunar origin",
            "Lunar petrology",
            "Lunar phase",
            "Lunar probes",
            "Lunar rays",
            "Lunar rilles",
            "Lunar science",
            "Lunar seismology",
            "Lunar surface",
            "Lunar theory",
            "Lunar transient phenomena",
            "Lyman alpha forest",
            "Lyman limit systems",
            "Lyman-alpha forest clouds",
            "Lyman-alpha galaxies",
            "Lyman-break galaxies",
            "M dwarf stars",
            "M giant stars",
            "M stars",
            "M subdwarf stars",
            "M subgiant stars",
            "M supergiant stars",
            "M-sigma relation",
            "Mach-Zehnder interferometers",
            "Magellanic Clouds",
            "Magellanic irregular galaxies",
            "Magellanic Stream",
            "Magnetars",
            "Magnetic anomalies",
            "Magnetic fields",
            "Magnetic stars",
            "Magnetic variable stars",
            "Magnetohydrodynamical simulations",
            "Magnetohydrodynamics",
            "Magnetospheric radio emissions",
            "Magnitude",
            "Main belt asteroids",
            "Main sequence",
            "Main sequence stars",
            "Major axis",
            "Makemake",
            "Maksutov telescopes",
            "Manganese stars",
            "Mantle",
            "Markarian galaxies",
            "Markov chain Monte Carlo",
            "Mars",
            "Mars trojans",
            "Martian satellites",
            "Mascon",
            "Mass ratio",
            "Mass spectrometers",
            "Mass spectrometry",
            "Mass-to-light ratio",
            "Massive stars",
            "Matter density",
            "Maunder minimum",
            "Maximal Kerr black holes",
            "Maximum likelihood estimation",
            "Me stars",
            "Me variable stars",
            "Mean anomaly",
            "Mean matter density",
            "Measurement error model",
            "Medium band photometry",
            "Megalithic astronomy",
            "Megamasers",
            "Mercury (planet)",
            "Mercury-manganese stars",
            "Meridian",
            "Meridian circles",
            "Mesogranulation",
            "Mesopause",
            "Mesosphere",
            "Metal line absorbers",
            "Metallicity",
            "Meteor radiants",
            "Meteor showers",
            "Meteor streams",
            "Meteor trails",
            "Meteorite composition",
            "Meteorites",
            "Meteoroid dust clouds",
            "Meteoroids",
            "Meteors",
            "Methane",
            "Metropolis-Hastings",
            "Michelson interferometers",
            "Michelson interferometry",
            "Microgravity",
            "Micrometeorites",
            "Micrometeoroids",
            "Milky Way dark matter halo",
            "Milky Way disk",
            "Milky Way dynamics",
            "Milky Way evolution",
            "Milky Way formation",
            "Milky Way Galaxy",
            "Milky Way Galaxy fountains",
            "Milky Way Galaxy physics",
            "Milky Way magnetic fields",
            "Milky Way mass",
            "Milky Way rotation",
            "Milky Way stellar halo",
            "Millimeter astronomy",
            "Millisecond pulsars",
            "Mini Neptunes",
            "Minimum chi-squared",
            "Minimum spanning tree",
            "Minor axis",
            "Minor planets",
            "Mira variable stars",
            "Missing mass",
            "Mixture model",
            "Model selection",
            "Modified Newtonian dynamics",
            "Moldavites",
            "Molecular clouds",
            "Molecular gas",
            "Molecular physics",
            "Molecular spectroscopy",
            "Molecule destruction",
            "Molecule formation",
            "Morgan-Keenan classification",
            "Moving cluster parallax",
            "Moving clusters",
            "Multi-color photometry",
            "Multi-periodic pulsation",
            "Multi-periodic variable stars",
            "Multiple mirror telescopes",
            "Multiple stars",
            "Multivariate analysis",
            "N galaxies",
            "N stars",
            "N-body problem",
            "N-body simulations",
            "Nadir",
            "Naked singularities",
            "Narrow band photometry",
            "Natural decay",
            "Natural satellites (Extrasolar)",
            "Natural satellites (Solar system)",
            "Nautical almanacs",
            "Navarro-Frenk-White profile",
            "Near infrared astronomy",
            "Near ultraviolet astronomy",
            "Near-Earth objects",
            "Nebulae",
            "Neptune",
            "Neptune trojans",
            "Neptunian satellites",
            "Nested sampling",
            "Neural networks",
            "Neutral hydrogen clouds",
            "Neutrino astronomy",
            "Neutrino decoupling",
            "Neutrino masses",
            "Neutrino oscillations",
            "Neutrino telescopes",
            "Neutron interferometry",
            "Neutron star cores",
            "Neutron stars",
            "Newtonian cosmology",
            "Newtonian gravitation",
            "Newtonian telescopes",
            "Night sky brightness",
            "Night vision",
            "Nitrous oxide",
            "Noctilucent clouds",
            "Non-Gaussianity",
            "Non-radial pulsations",
            "Non-standard theories of gravity",
            "Non-thermal radiation sources",
            "Nonclassical interferometry",
            "Nonlinear regression",
            "Nonparametric hypothesis tests",
            "Nonparametric inference",
            "Nonrotating black holes",
            "Nonstandard evolution",
            "Normal distribution",
            "North celestial pole",
            "North ecliptic pole",
            "North galactic pole",
            "Nova-like variable stars",
            "Novae",
            "Nuclear abundances",
            "Nuclear astrophysics",
            "Nuclear physics",
            "Nuclear reaction cross sections",
            "Nucleated dwarf galaxies",
            "Nucleosynthesis",
            "O associations",
            "O clusters",
            "O dwarf stars",
            "O giant stars",
            "O stars",
            "O subdwarf stars",
            "O subgiant stars",
            "O supergiant stars",
            "OB associations",
            "OB stars",
            "OB supergiant stars",
            "Oblateness",
            "Oblique rotators",
            "Observational astronomy",
            "Observational cosmology",
            "Observatories",
            "Occultation",
            "Occulting disks",
            "Ocean planets",
            "Ocean tides",
            "Ocean-atmosphere interactions",
            "Oe stars",
            "Oef stars",
            "Of stars",
            "OH/IR stars",
            "Oort cloud",
            "Oort cloud objects",
            "Oort constants",
            "Open source software",
            "Open star clusters",
            "Open universe",
            "Opik theory",
            "Opposition",
            "Optical bursts",
            "Optical double stars",
            "Optical flares",
            "Optical identification",
            "Optical interferometry",
            "Optical observation",
            "Optical observatories",
            "Optical phase shifting interferometry",
            "Optical position",
            "Optical pulsars",
            "Optical telescopes",
            "Orbit determination",
            "Orbital anomalies",
            "Orbital elements",
            "Orbital evolution",
            "Orbital motion",
            "Orbital nodes",
            "Orbital resonances",
            "Orbital theory",
            "Orbiters",
            "Orbits",
            "Orcus",
            "Origin of the universe",
            "Orreries",
            "Oscillating universe",
            "Osculating orbit",
            "Osculatory elements",
            "Outer planets",
            "Outlier detection",
            "Overabundances",
            "Oxygen burning",
            "Ozone layer",
            "P-process",
            "Parabolic orbit",
            "Parallax",
            "Parallel field",
            "Parametric hypothesis tests",
            "Pareto distribution",
            "Parsec",
            "Partial eclipses",
            "Particle astrophysics",
            "Particle physics",
            "Peculiar variable stars",
            "Penrose limit",
            "Penrose process",
            "Penumbra",
            "Periapsis",
            "Periastron",
            "Perigee",
            "Perihelion",
            "Period determination",
            "Period search",
            "Periodic orbit",
            "Periodic variable stars",
            "Perseus Cluster",
            "Perturbation methods",
            "PG 1159 stars",
            "Phase angle",
            "Phase defect",
            "Phase dispersion minimization",
            "Phase effect",
            "Phase error",
            "Phase switching",
            "Philosophy of astronomy",
            "Photodissociation regions",
            "Photoelectric magnitude",
            "Photoelectric photometry",
            "Photoelectron spectroscopy",
            "Photogrammetry",
            "Photographic astrometry",
            "Photographic magnitude",
            "Photographic photometry",
            "Photoheliographs",
            "Photoionization",
            "Photometer",
            "Photometric parallax",
            "Photometric standard stars",
            "Photometric systems",
            "Photometry",
            "Photon decoupling",
            "Photon sphere",
            "Photovisual magnitude",
            "Pickup ions",
            "Plages",
            "Planet formation",
            "Planet hosting stars",
            "Planetary alignment",
            "Planetary atmospheres",
            "Planetary boundary layers",
            "Planetary bow shocks",
            "Planetary cores",
            "Planetary interior",
            "Planetary magnetosphere",
            "Planetary nebulae",
            "Planetary nebulae nuclei",
            "Planetary polar regions",
            "Planetary probes",
            "Planetary ring divisions",
            "Planetary rings",
            "Planetary science",
            "Planetary structure",
            "Planetary system formation",
            "Planetary theory",
            "Planetesimals",
            "Plasma astrophysics",
            "Plasma clouds",
            "Plasma jets",
            "Plasma physics",
            "Plasmapause",
            "Plate tectonics",
            "Plutinos",
            "Pluto",
            "Plutoids",
            "Pogson scale",
            "Pointing accuracy",
            "Pointing error",
            "Poisson distribution",
            "Polar caps",
            "Polar jets",
            "Polar orbit",
            "Polar tides",
            "Polarimeters",
            "Polarimetry",
            "Polycyclic aromatic hydrocarbons",
            "Polytropes",
            "Poor galaxy clusters",
            "Population I stars",
            "Population II Cepheid variable stars",
            "Population II stars",
            "Population III stars",
            "Position angle",
            "Post-asymptotic giant branch",
            "Posterior distribution",
            "pp waves",
            "Pre-biotic astrochemistry",
            "Pre-main sequence",
            "Pre-main sequence stars",
            "Pre-solar nebulae",
            "Primordial black holes",
            "Primordial galaxies",
            "Primordial magnetic fields",
            "Principal component analysis",
            "Prior distribution",
            "Private software",
            "Proper motions",
            "Proplyds",
            "Protoclusters",
            "Protogalaxies",
            "Proton-proton reaction",
            "Protoplanetary disks",
            "Protoplanetary nebulae",
            "Protostars",
            "Ptolemy stones",
            "Public domain software",
            "Publicly available software",
            "Pulsar planets",
            "Pulsar timing method",
            "Pulsars",
            "Pulsating variable stars",
            "Pulsation frequency method",
            "Pulsation modes",
            "Purkinje effect",
            "PV Telescopii variable stars",
            "Quadrants",
            "Quantum cosmology",
            "Quantum gravity",
            "Quaoar",
            "Quasar absorption line spectroscopy",
            "Quasar microlensing",
            "Quasar-galaxy pairs",
            "Quasars",
            "Quasinormal modes",
            "Quenched galaxies",
            "Quiescent solar prominence",
            "Quiet solar chromosphere",
            "Quiet solar corona",
            "Quiet sun",
            "Quintessence",
            "R associations",
            "R Coronae Borealis variable stars",
            "R stars",
            "R-process",
            "Radar astronomy",
            "Radar telescopes",
            "Radial pulsations",
            "Radial velocity",
            "Radiative braking",
            "Radiative magnetohydrodynamics",
            "Radiative processes",
            "Radiative processes",
            "Radiative recombination",
            "Radiative transfer",
            "Radiative transfer equation",
            "Radiative transfer simulations",
            "Radical-radical recombination",
            "Radio astrometry",
            "Radio astronomy",
            "Radio bursts",
            "Radio continuum emission",
            "Radio cores",
            "Radio galaxies",
            "Radio hot spots",
            "Radio interferometers",
            "Radio interferometry",
            "Radio jets",
            "Radio lobes",
            "Radio loud quasars",
            "Radio observatories",
            "Radio occultation",
            "Radio plumes",
            "Radio pulsars",
            "Radio quiet quasars",
            "Radio receivers",
            "Radio source catalogs",
            "Radio source counts",
            "Radio sources",
            "Radio spectroscopy",
            "Radio telescopes",
            "Radio transient sources",
            "Radioheliographs",
            "Random Forests",
            "Rapid bursts",
            "Rapid stellar oscillations",
            "Rapidly oscillating Ap star",
            "Reaction catalysts",
            "Reaction rates",
            "Recombination",
            "Recombination (cosmology)",
            "Recurrent novae",
            "Red dwarf flare stars",
            "Red giant branch",
            "Red giant bump",
            "Red giant clump",
            "Red giant stars",
            "Red giant tip",
            "Red noise",
            "Red sequence galaxies",
            "Red straggler stars",
            "Red supergiant stars",
            "Reddened stars",
            "Reddening law",
            "Redshift surveys",
            "Redshifted",
            "Reflecting telescopes",
            "Reflection nebulae",
            "Refracting telescopes",
            "Regression",
            "Reionization",
            "Reissner-Nordstrom black holes",
            "Relativistic aberration",
            "Relativistic binary stars",
            "Relativistic cosmology",
            "Relativistic disks",
            "Relativistic fluid dynamics",
            "Relativistic jets",
            "Relativistic mechanics",
            "Relativistic stars",
            "Relativity",
            "Relaxation time",
            "Remote telescope astrophotography",
            "Resonant Kuiper belt objects",
            "Reverberation mapping",
            "RGB photometry",
            "RGU photometry",
            "Rich galaxy clusters",
            "Right ascension",
            "Ring galaxies",
            "Ring nebulae",
            "Ring singularities",
            "Ritchey-Chretien telescopes",
            "Robust regression",
            "Roche limit",
            "Roche lobe",
            "Rotating black holes",
            "Rotating shells",
            "Rotation powered pulsars",
            "Rovers",
            "RR Lyrae variable stars",
            "RRab variable stars",
            "RRc variable stars",
            "RRd variable stars",
            "RS Canum Venaticorum variable stars",
            "Runaway stars",
            "RV Tauri variable stars",
            "S Doradus stars",
            "S stars",
            "S-process",
            "Sagittarius dwarf spheroidal galaxy",
            "Sampling distribution",
            "Saros cycle",
            "Satellite formation",
            "Saturn",
            "Saturnian satellites",
            "Scalar-tensor-vector gravity",
            "Scale height",
            "Scaling relations",
            "Scattered disk objects",
            "Schmidt cameras",
            "Schmidt-Cassegrain telescopes",
            "Schonberg-Chandrasekhar limit",
            "Schwarzschild black holes",
            "Schwarzschild metric",
            "Schwarzschild radius",
            "Sculptor dwarf elliptical galaxy",
            "Seasonal phenomena",
            "Secondary cosmic rays",
            "Secular parallax",
            "Sedna",
            "Selenology",
            "Semi-barium stars",
            "Semi-detached binary stars",
            "Semi-regular variable stars",
            "Semimajor axis",
            "Semiminor axis",
            "Seyfert galaxies",
            "Shadow bands",
            "Shell burning",
            "Shell stars",
            "Shepherd satellites",
            "Shocks",
            "Short period comets",
            "Short period variable stars",
            "Siderostats",
            "Sigma8",
            "Silicate grains",
            "Silicon burning",
            "Silicon monoxide masers",
            "Silicon stars",
            "Single X-ray stars",
            "Single-dish antennas",
            "Single-linkage hierarchical clustering",
            "Sky brightness",
            "Sky noise",
            "Sky surveys",
            "Sloan photometry",
            "Slow irregular variable stars",
            "Slow novae",
            "Slow solar wind",
            "Small Magellanic Cloud",
            "Small solar system bodies",
            "Smoothing",
            "Sociology of astronomy",
            "Soft gamma-ray repeaters",
            "Software available on request",
            "Software documentation",
            "Software licensing",
            "Software tutorials",
            "Solar abundances",
            "Solar active region filaments",
            "Solar active region magnetic fields",
            "Solar active region velocity fields",
            "Solar active regions",
            "Solar activity",
            "Solar analogs",
            "Solar atmosphere",
            "Solar atmospheric motions",
            "Solar chromosphere",
            "Solar chromospheric heating",
            "Solar constant",
            "Solar convective zone",
            "Solar core",
            "Solar corona",
            "Solar coronal heating",
            "Solar coronal holes",
            "Solar coronal lines",
            "Solar coronal loops",
            "Solar coronal mass ejection shocks",
            "Solar coronal mass ejections",
            "Solar coronal plumes",
            "Solar coronal radio emission",
            "Solar coronal seismology",
            "Solar coronal streamers",
            "Solar coronal transients",
            "Solar coronal waves",
            "Solar cycle",
            "Solar differential rotation",
            "Solar dynamo",
            "Solar E coronal region",
            "Solar eclipses",
            "Solar electromagnetic emission",
            "Solar energetic particles",
            "Solar evolution",
            "Solar extreme ultraviolet emission",
            "Solar F coronal region",
            "Solar faculae",
            "Solar fibrils",
            "Solar filament eruptions",
            "Solar filaments",
            "Solar flare spectra",
            "Solar flares",
            "Solar gamma-ray emission",
            "Solar granulation",
            "Solar granules",
            "Solar instruments",
            "Solar interior",
            "Solar K coronal region",
            "Solar M coronal region",
            "Solar macrospicules",
            "Solar magnetic bright points",
            "Solar magnetic fields",
            "Solar magnetic flux emergence",
            "Solar magnetic reconnection",
            "Solar mass",
            "Solar meridional circulation",
            "Solar motion",
            "Solar mottles",
            "Solar nebulae",
            "Solar neighborhood",
            "Solar neutrino problem",
            "Solar neutrinos",
            "Solar neutrons",
            "Solar observatories",
            "Solar optical telescopes",
            "Solar oscillations",
            "Solar parallax",
            "Solar particle emission",
            "Solar photosphere",
            "Solar physics",
            "Solar prominences",
            "Solar radiation",
            "Solar radiative zone",
            "Solar radio emission",
            "Solar radio flares",
            "Solar radio telescopes",
            "Solar radius",
            "Solar rotation",
            "Solar spectral irradiance",
            "Solar spicules",
            "Solar storm",
            "Solar surface",
            "Solar system",
            "Solar system astronomy",
            "Solar system formation",
            "Solar system planets",
            "Solar telescopes",
            "Solar transition region",
            "Solar ultraviolet emission",
            "Solar white-light flares",
            "Solar wind",
            "Solar wind termination",
            "Solar X-ray emission",
            "Solar x-ray flares",
            "Solar-planetary interactions",
            "Solar-terrestrial interactions",
            "Solid matter physics",
            "Solstice",
            "South celestial pole",
            "South ecliptic pole",
            "South galactic pole",
            "Space astrometry",
            "Space debris",
            "Space observatories",
            "Space plasmas",
            "Space probes",
            "Space research",
            "Space telescopes",
            "Space vehicle instruments",
            "Space vehicles",
            "Space weather",
            "Spacetime metric",
            "Spatial point processes",
            "Special relativity",
            "Speckle interferometry",
            "Spectral index",
            "Spectral line identification",
            "Spectral line lists",
            "Spectrometers",
            "Spectrophotometric standards",
            "Spectrophotometry",
            "Spectropolarimetry",
            "Spectroscopic binary stars",
            "Spectroscopy",
            "Spiral arms",
            "Spiral galaxies",
            "Spiral pitch angle",
            "Spokes",
            "SRa variable stars",
            "SRb variable stars",
            "SRc variable stars",
            "SRd variable stars",
            "SRS variable stars",
            "Standard candles",
            "Standard stars",
            "Star atlases",
            "Star clusters",
            "Star counts",
            "Star formation",
            "Star forming regions",
            "Starburst galaxies",
            "Starlight polarization",
            "Starspots",
            "Statistical parallax",
            "Steady-state theory",
            "Stefan's quintet",
            "Stellar abundances",
            "Stellar accretion",
            "Stellar accretion disks",
            "Stellar activity",
            "Stellar ages",
            "Stellar associations",
            "Stellar astronomy",
            "Stellar atmospheres",
            "Stellar atmospheric opacity",
            "Stellar bow shocks",
            "Stellar bridges",
            "Stellar chromospheres",
            "Stellar classification",
            "Stellar colors",
            "Stellar convection envelopes",
            "Stellar convective shells",
            "Stellar convective zones",
            "Stellar cores",
            "Stellar coronae",
            "Stellar coronal dimming",
            "Stellar coronal holes",
            "Stellar coronal lines",
            "Stellar coronal loops",
            "Stellar coronal mass ejections",
            "Stellar coronal plumes",
            "Stellar diffusion",
            "Stellar distance",
            "Stellar dynamics",
            "Stellar E coronal regions",
            "Stellar effective temperatures",
            "Stellar evolution",
            "Stellar evolutionary models",
            "Stellar evolutionary tracks",
            "Stellar evolutionary types",
            "Stellar F coronal regions",
            "Stellar faculae",
            "Stellar feedback",
            "Stellar flares",
            "Stellar gas distribution",
            "Stellar granulation",
            "Stellar granules",
            "Stellar inner cores",
            "Stellar interiors",
            "Stellar jets",
            "Stellar K coronal regions",
            "Stellar kinematics",
            "Stellar luminosities",
            "Stellar M coronal regions",
            "Stellar magnetic fields",
            "Stellar mass black holes",
            "Stellar mass functions",
            "Stellar mass loss",
            "Stellar masses",
            "Stellar motion",
            "Stellar nucleosynthesis",
            "Stellar oscillations",
            "Stellar parallax",
            "Stellar phenomena",
            "Stellar photometry",
            "Stellar photospheres",
            "Stellar physics",
            "Stellar populations",
            "Stellar processes",
            "Stellar properties",
            "Stellar pulsations",
            "Stellar radii",
            "Stellar remnants",
            "Stellar rings",
            "Stellar rotation",
            "Stellar spectral lines",
            "Stellar spectral types",
            "Stellar structures",
            "Stellar surfaces",
            "Stellar tracking devices",
            "Stellar types",
            "Stellar wind bubbles",
            "Stellar winds",
            "Stellar x-ray flares",
            "Stellar-interstellar interactions",
            "Stone circles",
            "Stratopause",
            "Stratosphere",
            "Strong gravitational lensing",
            "Strontium stars",
            "Stromgren photometric system",
            "Stromgren spheres",
            "SU Ursae Majoris stars",
            "Subdwarf stars",
            "Subgiant stars",
            "Submillimeter astronomy",
            "Substellar companion stars",
            "Summer solstice",
            "Sunspot cycle",
            "Sunspot flow",
            "Sunspot groups",
            "Sunspot number",
            "Sunspots",
            "Sunyaev-Zeldovich effect",
            "Super Earths",
            "Superbubbles",
            "Superclusters",
            "Supergalactic coordinate system",
            "Supergalactic latitude",
            "Supergalactic longitude",
            "Supergiant stars",
            "Supergranulation",
            "Supermassive black holes",
            "Supernova dynamics",
            "Supernova neutrinos",
            "Supernova remnants",
            "Supernovae",
            "Support vector machine",
            "Surface gravity",
            "Surface photometry",
            "Surveys",
            "Survival analysis",
            "SX Arietis variable stars",
            "SX Phoenicis variable stars",
            "Symbiotic binary stars",
            "Symbiotic novae",
            "Synodic period",
            "Syzygy",
            "T associations",
            "T dwarfs",
            "T subdwarfs",
            "T Tauri stars",
            "Tailed radio galaxies",
            "Technetium stars",
            "Teharonhiawako",
            "Tektites",
            "Telescope focal plane photography",
            "Telescope mounts",
            "Telescopes",
            "Termination shock",
            "Tertiary stars",
            "The Moon",
            "The Sun",
            "Theoretical models",
            "Theoretical techniques",
            "Thermosphere",
            "Three-body problem",
            "Tidal disruption",
            "Tidal distortion",
            "Tidal friction",
            "Tidal interaction",
            "Tidal radius",
            "Tidal tails",
            "Tides",
            "Time series analysis",
            "Timing variation methods",
            "Total eclipses",
            "Trans-Neptunian objects",
            "Trans-Planckian physics",
            "Transient detection",
            "Transient sources",
            "Transit duration variation method",
            "Transit instruments",
            "Transit photometry",
            "Transit timing variation method",
            "Transition probabilities",
            "Transits",
            "Triangulum Galaxy",
            "Trigonometric parallax",
            "Trinary stars",
            "Trojan asteroids",
            "Trojan planets",
            "Tropopause",
            "Troposphere",
            "True anomaly",
            "True position",
            "Turnoff point",
            "Twilight",
            "Two-body problem",
            "Two-color diagrams",
            "Two-dimensional gravity",
            "Two-point correlation function",
            "Twotinos",
            "Type Ia supernovae",
            "Type Ib supernovae",
            "Type Ic supernovae",
            "Type II supernovae",
            "U Geminorum stars",
            "Ultra-high-energy cosmic radiation",
            "Ultracompact dwarf galaxies",
            "Ultraluminous infrared galaxies",
            "Ultraviolet astronomy",
            "Ultraviolet color",
            "Ultraviolet extinction",
            "Ultraviolet observatories",
            "Ultraviolet photometry",
            "Ultraviolet sources",
            "Ultraviolet surveys",
            "Ultraviolet telescopes",
            "Ultraviolet transient sources",
            "Umbra",
            "Unbarred spiral galaxies",
            "Uncertainty bounds",
            "Uncharged black holes",
            "Underabundances",
            "Upper atmosphere",
            "Upsilon Sagittarii stars",
            "Uranian satellites",
            "Uranus",
            "Urca process",
            "Ursa Minor dwarf spheroidal galaxy",
            "UU Herculis stars",
            "UV Ceti stars",
            "UV Persei stars",
            "UX Ursae Majoris stars",
            "Van Allen radiation belt",
            "Variable radiation sources",
            "Variable star period change",
            "Variable stars",
            "Varuna",
            "Venus",
            "Vernal equinox",
            "Vertical circle",
            "Very Large Array",
            "Very Large Telescope",
            "Very long baseline interferometers",
            "Very long baseline interferometry",
            "Very small grains",
            "Vilnius photometry",
            "Virgo Cluster",
            "Virgo Supercluster",
            "Virtual observatories",
            "Visibility function",
            "Visible astronomy",
            "Visible sources",
            "Visual binary stars",
            "Visual observation",
            "Voids",
            "Volcanoes",
            "von Zeipel theorem",
            "Voronoi tessellation",
            "VY Sculpturis stars",
            "W Ursae Majoris variable stars",
            "W Virginis variable stars",
            "Walraven photometry",
            "Warm dark matter",
            "Warm ionized medium",
            "Warm neutral medium",
            "Warm-hot intergalactic medium",
            "Water masers",
            "Water vapor",
            "Waveband photometry",
            "Wavelet analysis",
            "WC stars",
            "WCN stars",
            "Weak G band stars",
            "Weak gravitational lensing",
            "Weak-line T Tauri stars",
            "White dwarf stars",
            "Wide binary stars",
            "Wide-field telescopes",
            "Wilson effect",
            "Winter solstice",
            "WN stars",
            "Wolf diagram",
            "Wolf-Rayet stars",
            "Wormholes",
            "WZ Sagittae stars",
            "X-ray active galactic nuclei",
            "X-ray astronomy",
            "X-ray binary stars",
            "X-ray bright point",
            "X-ray bursters",
            "X-ray bursts",
            "X-ray detectors",
            "X-ray identification",
            "X-ray novae",
            "X-ray observatories",
            "X-ray photometry",
            "X-ray point sources",
            "X-ray quasars",
            "X-ray sources",
            "X-ray stars",
            "X-ray surveys",
            "X-ray telescopes",
            "X-ray transient sources",
            "Xenobiology",
            "Y dwarfs",
            "Yellow hypergiant stars",
            "Yellow straggler stars",
            "Yerkes classification",
            "Young disk Cepheid variable stars",
            "Young massive clusters",
            "Young star clusters",
            "Young stellar objects",
            "Z Andromedae stars",
            "Z Camelopardalis stars",
            "Zeeman-Doppler imaging",
            "Zenith",
            "Zenith hourly rate",
            "Zenith telescopes",
            "Zenith tubes",
            "Zero-age horizontal branch stars",
            "Zero-age main sequence stars",
            "Zirconium stars",
            "Zodiacal cloud",
            "Zone of totality",
            "ZZ Ceti stars"
]
